name: $(Build.DefinitionName)-$(Date:yyyyMMdd)-$(BuildID)

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: ServiceConnection
    value: AzureServiceConnection
  - name: DataFactoryNameDev
    value: df-adf-csv-to-cosmos-dev
  - name: ResourceGroupDev
    value: rg-adf-csv-to-cosmos-adf-dev
  - name: Location
    value: japaneast

stages:
  - stage: Build
    variables:
      - group: dev # Should contain SubscriptionId Variable
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            displayName: Install Node.js
            inputs:
              versionSpec: 16.x
          - task: Npm@1
            displayName: Install npm Packages
            inputs:
              command: install
              verbose: true
          # Validates all of the ADF resources in the repository. You will get the same validation errors as when "Validate All" is clicked
          - task: Npm@1
            displayName: Validate ADF Resources
            inputs:
              command: custom
              customCommand: run build validate $(Build.Repository.LocalPath)/datafactory /subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroupDev)/providers/Microsoft.DataFactory/factories/$(DataFactoryNameDev)
          # Validate and then generate the ARM template into the destination folder. Same as clicking "Publish" from UX
          # The ARM template generated is not published to the ‘Live’ version of the factory.
          - task: Npm@1
            displayName: Validate and Generate ARM Template
            inputs:
              command: custom
              customCommand: run build export $(Build.Repository.LocalPath)/datafactory /subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroupDev)/providers/Microsoft.DataFactory/factories/$(DataFactoryNameDev) output
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/output
              artifact: arm
              publishLocation: pipeline
  - stage: DEV
    variables:
      - group: dev
    jobs:
      - deployment: Deploy
        displayName: Deploy Data Factory
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              # Stop any triggers before deploying
              - task: AzurePowerShell@5
                displayName: Stop Triggers
                inputs:
                  azureSubscription: $(ServiceConnection)
                  scriptType: filePath
                  scriptPath: $(System.DefaultWorkingDirectory)/scripts/stop-triggers.ps1
                  scriptArguments:
                    -DataFactoryName   $(DataFactoryNameDev) `
                    -ResourceGroupName $(ResourceGroupDev) `
                    -ArmTemplate '$(Pipeline.Workspace)/arm/ARMTemplateForFactory.json'
                  azurePowerShellVersion: latestVersion
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: Deploy ARM Template
                inputs:
                  azureResourceManagerConnection: $(ServiceConnection)
                  subscriptionId: $(SubscriptionId)
                  resourceGroupName: $(ResourceGroupDev)
                  location: $(Location)
                  csmFile: $(Pipeline.Workspace)/arm/ARMTemplateForFactory.json
                  csmParametersFile: $(Pipeline.Workspace)/arm/ARMTemplateParametersForFactory.json