name: $(Build.DefinitionName)-$(Date:yyyyMMdd)-$(BuildID)

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: ServiceConnection
    value: AzureServiceConnection
  - name: DataFactoryNameDev
    value: df-adf-csv-to-cosmos-dev
  - name: ResourceGroupDev
    value: rg-adf-csv-to-cosmos-dev
  - name: Location
    value: japaneast

stages:
  - stage: Build
    variables:
      - group: dev # Should contain SubscriptionId Variable
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            displayName: Install Node.js
            inputs:
              versionSpec: 16.x
          - task: Npm@1
            displayName: Install npm Packages
            inputs:
              command: install
              verbose: true
          # Validates all of the ADF resources in the repository. You will get the same validation errors as when "Validate All" is clicked
          - task: Npm@1
            displayName: Validate ADF Resources
            inputs:
              command: custom
              customCommand: run build validate $(Build.Repository.LocalPath)/datafactory /subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroupDev)/providers/Microsoft.DataFactory/factories/$(DataFactoryNameDev)
          # Validate and then generate the ARM template into the destination folder. Same as clicking "Publish" from UX
          # The ARM template generated is not published to the ‘Live’ version of the factory.
          - task: Npm@1
            displayName: Validate and Generate ARM Template
            inputs:
              command: custom
              customCommand: run build export $(Build.Repository.LocalPath)/datafactory /subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroupDev)/providers/Microsoft.DataFactory/factories/$(DataFactoryNameDev) output
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/output
              artifact: arm
              publishLocation: pipeline
  - stage: DEV
    variables:
      - group: dev
      - name: Environment
        value: dev
    jobs:
      - deployment: Deploy
        displayName: Deploy Data Factory
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              # Stop any triggers before deploying
              - task: AzurePowerShell@5
                displayName: Stop Triggers
                inputs:
                  azureSubscription: $(ServiceConnection)
                  scriptType: filePath
                  scriptPath: $(System.DefaultWorkingDirectory)/scripts/start-stop-triggers.ps1
                  scriptArguments:
                    -DataFactoryName   $(DataFactoryNameDev) `
                    -ResourceGroupName $(ResourceGroupDev) `
                    -armTemplate '$(Pipeline.Workspace)/arm/ARMTemplateForFactory.json' `
                    -predeployment $true `
                    -deleteDeployment $false
                  azurePowerShellVersion: latestVersion
              - task: AzureCLI@2
                displayName: Deploy ARM Template
                inputs:
                  azureSubscription: $(ServiceConnection)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    az deployment group create \
                      --resource-group $(ResourceGroupDev) \
                      --template-file $(Pipeline.Workspace)/arm/ARMTemplateForFactory.json \
                      --name adf-csv-to-cosmos-adf-$(Build.BuildId)-$(Environment) \
                      --parameters $(Pipeline.Workspace)/arm/ARMTemplateParametersForFactory.json
                      --parameters BlobPrivateEndpoint_properties_privateLinkResourceId=/subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroupDev)/providers/Microsoft.Storage/storageAccounts/adfcsvcosmos$(Environment)
              # Approve Private Link Connections
              - task: AzurePowerShell@5
                displayName: Approve Private Endpoint Connections
                inputs:
                  azureSubscription: $(ServiceConnection)
                  scriptType: filePath
                  scriptPath: $(System.DefaultWorkingDirectory)/scripts/approve-private-link-connections.ps1
                  scriptArguments:
                    -ResourceId '/subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroupDev)/providers/Microsoft.Storage/storageAccounts/adfcsvcosmos$(Environment)'
                  azurePowerShellVersion: latestVersion